version: '3'
services:
  web:
    container_name: easyadmin
    image: easyadmin
    build: "."
    restart: always
    ports:
      - "8000:7000"
    volumes:
      - ./:/app
      - /var/www/admin-easylogin/static:/static
    command: bash -c "python manage.py collectstatic --no-input && sh gunicorn.sh"
