# Generated by Django 2.1 on 2021-01-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15)),
                ('dst_social_id', models.BigIntegerField()),
                ('status', models.CharField(max_length=15)),
                ('nonce', models.CharField(max_length=32)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.App')),
            ],
            options={
                'db_table': 'associate_logs',
            },
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15)),
                ('callback_uri', models.CharField(max_length=2047)),
                ('callback_if_failed', models.CharField(db_column='callback_failed', max_length=2047, null=True)),
                ('nonce', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=15)),
                ('is_login', models.SmallIntegerField()),
                ('intent', models.CharField(max_length=32, null=True)),
                ('platform', models.CharField(max_length=8)),
                ('oa1_token', models.CharField(max_length=1023, null=True)),
                ('oa1_secret', models.CharField(max_length=1023, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.App')),
            ],
            options={
                'db_table': 'auth_logs',
            },
        ),
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4095, null=True)),
                ('ua', models.CharField(max_length=1023, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('ref_id', models.IntegerField()),
            ],
            options={
                'db_table': 'journal_logs',
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15)),
                ('profile_id', models.CharField(db_column='pk', max_length=40, unique=True)),
                ('attrs', models.CharField(max_length=8191)),
                ('scope_id', models.CharField(max_length=255)),
                ('last_authorized_at', models.DateTimeField(db_column='authorized_at', null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('verified', models.SmallIntegerField(default=0)),
                ('linked_at', models.DateTimeField(null=True)),
                ('alias', models.BigIntegerField()),
                ('deleted', models.SmallIntegerField(default=0)),
                ('prohibited', models.SmallIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.App')),
            ],
            options={
                'db_table': 'social_profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(db_column='pk', max_length=128)),
                ('deleted', models.SmallIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.App')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15)),
                ('oa_version', models.SmallIntegerField()),
                ('token_type', models.CharField(max_length=15)),
                ('access_token', models.CharField(max_length=2047, null=True)),
                ('refresh_token', models.CharField(max_length=2047, null=True)),
                ('id_token', models.CharField(max_length=2047, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('oa1_token', models.CharField(max_length=1023, null=True)),
                ('oa1_secret', models.CharField(max_length=1023, null=True)),
                ('social_profile', models.ForeignKey(db_column='social_id', on_delete=django.db.models.deletion.CASCADE, to='loginapp.SocialProfile')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.SocialUser'),
        ),
        migrations.AddField(
            model_name='authlog',
            name='social_profile',
            field=models.ForeignKey(db_column='social_id', on_delete=django.db.models.deletion.CASCADE, to='loginapp.SocialProfile'),
        ),
    ]
