# Generated by Django 2.1 on 2018-08-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=67)),
                ('api_key', models.CharField(max_length=127)),
                ('callback_uri', models.URLField(max_length=2047)),
                ('allowed_ips', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=1023)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.App')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=7)),
                ('permission', models.CharField(max_length=1023)),
            ],
        ),
    ]
