# Generated by Django 2.1 on 2018-08-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='callback_uri',
            new_name='callback_uris',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='permission',
            new_name='permissions',
        ),
    ]
