# Generated by Django 2.1 on 2021-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_add_easycore_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
