# Generated by Django 2.2.17 on 2021-01-25 11:12

from django.db import migrations

from loginapp.init_providers import init_providers


def add_providers(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        init_providers(connection, cursor)


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_add_easy_core_models'),
    ]

    operations = [
        migrations.RunPython(code=add_providers)
    ]
