# Generated by Django 2.1 on 2018-08-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_app_channel_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='domain',
            new_name='name',
        ),
    ]
