# Generated by Django 2.1 on 2018-08-28 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20180827_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='permissions_required',
            field=models.CharField(default=django.utils.timezone.now, max_length=1023),
            preserve_default=False,
        ),
    ]
