# Generated by Django 2.1 on 2021-01-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20210111_1847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminsetting',
            table='easylogin_system_settings',
        ),
        migrations.AlterModelTable(
            name='app',
            table='easylogin_apps',
        ),
        migrations.AlterModelTable(
            name='associatelog',
            table='easylogin_associate_logs',
        ),
        migrations.AlterModelTable(
            name='authlog',
            table='easylogin_auth_logs',
        ),
        migrations.AlterModelTable(
            name='channel',
            table='easylogin_channels',
        ),
        migrations.AlterModelTable(
            name='journallog',
            table='easylogin_journal_logs',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='easylogin_providers',
        ),
        migrations.AlterModelTable(
            name='socialprofile',
            table='easylogin_social_profiles',
        ),
        migrations.AlterModelTable(
            name='socialuser',
            table='easylogin_users',
        ),
        migrations.AlterModelTable(
            name='token',
            table='easylogin_tokens',
        ),
        migrations.AlterModelTable(
            name='user',
            table='easylogin_admins',
        ),
    ]
