# Generated by Django 2.1 on 2021-01-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20210111_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('name', 'version')},
        ),
    ]
