# Generated by Django 2.1 on 2021-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_add_missing_datetime_cols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='is_login',
            field=models.SmallIntegerField(null=True),
        ),
    ]
