# Generated by Django 2.1 on 2021-01-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_alter_auth_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='social_profile',
            field=models.ForeignKey(db_column='social_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.SocialProfile'),
        ),
    ]
